### ISSUE TITLE
After installation, cannot execute bin/magento anymore

### ISSUE THREAD

**Issue by amenk** [techdivision/import-cli-simple#246]
**Describe the bug**

cannot call bin/magento anymore after installation

**To Reproduce**
1. composer require techdivision/import-cli-simple
2. call `bin/magento`

**Expected behavior**
No error

**Screenshots**

    PHP Fatal error:  Class 'Laminas\ServiceManager\AbstractPluginManager' not found in ....vendor/laminas/laminas-filter/src/FilterPluginManager.php on line 27

**Versions**

Magento: 2.3.4-p2

**Comment by pathmissing** [comment]
Hi @amenk, thank you for reporting this issue, I will have a look at it right away.

**Comment by amenk** [comment]
@pathmissing Even after uninstalling the package, `bin/magento` was broken, I was able to resolve it by deleting `vendor/laminas`. Seems to be something with the package-replacing?
Still I would like to give M2IF a try :)

**Comment by amenk** [comment]
I just learned that m2if is more like a seperate symfony application than a Magento plugin, so it might not make to much sense to pull the dependencies into a Magento 2 project, right?

**Comment by pathmissing** [comment]
@amenk You could use it as a standalone application required via composer, as a dependency in your Magento installation or you could use the import-cli-simple.phar file. All three ways are supported and should work out of the box.

The issue seems to be related to an incorrect set of dependencies, specifically `laminas/laminas-filter` which has a hard dependency on `laminas/laminas-servicemanager` which is not defined in the composer.json file (well it is defined as "require-dev" but not "require").

I am currently investigating why this issue did not occur before and how we can fix it. In the meantime you could require import-cli-simple outside of your project directory and execute your import commands from within your magento application root directory.

**Comment by pathmissing** [comment]
Although it is indeed problematic for `laminas/laminas-filter` to have a hard dependency on `laminas/laminas-servicemanager` without having a "required" declaration in composer.json, it is not the root cause of the issue. 

Back in january we accepted a pull request for using laminas-filter instead of the abandoned zend-filter: https://github.com/techdivision/import/commit/dbea2126572d575258aa190def4b6dadee6e81f1#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
This however leads to conflicts with other zendframework components which are requried by magento core until version 2.3.4. 

With 2.3.5, Magento replaced all zendframework components with their new laminas successors, which is why this issue has not been discovered earlier: https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-5-open-source.html

We will discuss possible solutions. Thanks again for the feedback!

**Comment by amenk** [comment]
Works, thanks :)

**Comment by wagnert** [comment]
@amenk Happy to hear that :)
