### ISSUE TITLE
Not mapped entity ID for SKU in variants_

### ISSUE THREAD

**Issue by wagnert** [techdivision/import-cli-simple#254]
Hi @wagnert, I ran a very simple CSV with only 2 configurable products and confirmed there were no hidden characters in the beginning of the file. When I ran the import, I get a new error message, but still about SKUs.

`Found not mapped entity ID for SKU  in file variants_20200616-000000_03.csv on line 2 in column(s) variant_parent_sku`

A record is being created in catalog_product_entity, but it is missing a sku. Some debugging shows the Lexer is picking up the skus from the CSV.

`TechDivision\Import\Adapter\Goodby\Lexer::parse (117) line = array (
  0 => 'sku',
  1 => 'product_type',
  2 => 'product_websites',
  3 => 'gift_message_available',
  4 => 'product_online',
  5 => 'visibility',
  6 => 'tax_class_name',
  7 => 'is_in_stock',
  8 => 'name',
  9 => 'attribute_set_code',
  10 => 'categories',
  11 => 'configurable_variations',
)
TechDivision\Import\Adapter\Goodby\Lexer::parse (117) line = array (
  0 => 'HR-TEST-04',
  1 => 'configurable',
  2 => 'base',
  3 => '2',
  4 => '1',
  5 => 'Catalog, Search',
  6 => 'Taxable Goods',
  7 => '1',
  8 => 'HR Configurable Test Product 04',
  9 => 'Default',
  10 => 'SHOP/KC Gear/KC Apparel',
  11 => 'sku=72021,pim_lenscolor=|sku=72011,pim_lenscolor=',
)
`
I traced the rows through TechDivision\Import\Adapter\Goodby\Interpreter::interpret and confirmed the sku is still in the data before and after notify(). This is called repeatedly. It appears once the variant process/subject is entered, that is when the sku goes missing.

`TechDivision\Import\Product\Variant\Observers\VariantSuperLinkObserver::process (80) ColumnKeys::VARIANT_PARENT_SKU=variant_parent_sku, parentSku =''

vendor/techdivision/import-product-variant/src/Observers/VariantSuperLinkObserver.php(87): TechDivision\Import\Product\Variant\Observers\VariantSuperLinkObserver->mapSku(NULL)`

Here is the CSV I'm working with.
[product-import_20200616-000000_03.zip](https://github.com/techdivision/import-cli-simple/files/4807734/product-import_20200616-000000_03.zip)

**Comment by wagnert** [comment]
Hi @HarmonyR, in general this means tha the SKU you've referenced in your CSV file is either not in the DB or in the CSV file. In your case, products `72021` and/or `72011` are not in the DB. So it's not possible to create the relation of the simples `72021` + `72011` to your configurable `HR-TEST-04`. Additionally I see in your file empty values for `pim_lenscolor` in the column `configurable_variations`, which will also lead to an error.

**Comment by HarmonyR** [comment]
Hi @wagnert all of the simple skus in the CSV are already in my DB. They are not in the CSV I provided as their own record. After researching how the native Magento Import works, I learned the simple products must be in the CSV before the configurable parent. I guess that is a requirement for M2IF as well?

The native Magento Import allows the attribute option values in the configurable_variations to not be specified. I ran the following CSV through the native Magento Import. The configurable products were created correctly and the simple products were linked for the first configurable.
[import-catalog-product_20200620_configs_test.txt](https://github.com/techdivision/import-cli-simple/files/4808669/import-catalog-product_20200620_configs_test.txt)

-- Start Rant --
I personally find it disappointing that I have to include the simple products in the CSV and I shouldn't have to specify the attribute option values since a lookup can be done. An admin could have changed the simple product option values in Magento and here I am using the original values in the CSV. I ran the native import with the wrong super attribute values specified (no errors) and it did not link the simples. If I have incorrect values in the configurable_variations field, the super attributes/product relations will not be created.

If I am importing thousands of configurable products, I will have no idea super attributes/product relations are not being set.
-- End Rant --

I ran the same CSV through M2IF and received the following error.
`Can't load product with SKU "HR-TEST-S1" in file variants_20200620-000000_01.csv on line 2`
I've attached the output from the run. You will see the variant_parent_sku column is still blank.
[variant_parent_sku_issue.zip](https://github.com/techdivision/import-cli-simple/files/4808679/variant_parent_sku_issue.zip)

**Comment by wagnert** [comment]
Hi @HarmonyR, you do not have to have the simples, that has to be related with the configurable, in the CSV file nor the order matters. It is enough when the simples are at least in the DB. You can verify that with one of our [example CSV files](https://github.com/techdivision/import-sample-data/blob/4.x/generic/data/products/delta/product-import_20161021-161909_01.csv) and the command
```sh
cd <magento-install-dir> \
  && cp <example-file-linked-above> var/importexport \
  && import-simple import:create:ok-file \
  && import-simple import:products
```
Again, I had a look at your file and you've a hidden char at the beginning. This results in corrupt data in the database
<img width="800" alt="db_rows" src="https://user-images.githubusercontent.com/287509/85224336-ed583200-b3c9-11ea-89d3-8e02daa050a4.png">

and curious error messages. After I've removed the incorrect char (by copying the content to a new file `product-import_20200621-140421_01.csv` (which is part of [ZIP](https://github.com/techdivision/import-cli-simple/files/4809410/import-cli-simple.254.zip) the import works as expected.

You can check that this is true by comparing the two files on the CLI using `cmp` or `diff` command
<img width="1672" alt="diff_and_cmp" src="https://user-images.githubusercontent.com/287509/85224334-eaf5d800-b3c9-11ea-8c65-040515618213.png">

BTW: I don't know what you mean with **-- Start Rant -- // -- End Rant --**, so it'll be nice if you can give me a short explanation about that :-)

**Comment by HarmonyR** [comment]
@wagnert Start/End Rant was me trying to vent in a funny way. My rant about having to do extra work when a lookup is available right in the DB. I think your comment was wrong, "Additionally I see in your file empty values for pim_lenscolor in the column configurable_variations, which will also lead to an error."  :-)

OMG I have spent days on this issue and here it turns out the real issue is encoding! My CSV files had an encoding of UTF-8-BOM (Microsoft Excel on Windows caused this). This was causing the extra invisible characters you were finding. I converted my CSVs to UTF-8 and they worked!

For anyone else following this issue, here are some important notes about importing configurable products (making this tool better than native Magento Import).

- The simple (child) products need to either exist in the Magento database or be included in the CSV, but not both.
  - Native Magento Import requires the simple (child) products to be in the CSV prior to the configurable product they are linked to.
- The configurable_variation_labels column is not required in the CSV. If the labels will not change from their default, no need to include this column.
  - This is the same with the native Magento Import.
- The attribute option values in the configurable_variations column do not need to be defined.
  - Meaning you can use something like "sku=simple01,attribute1=,attribute2=|sku=simple02,attribute1=,attribute2=" and the framework is intelligent enough to identify the value needed.

Thank you so much @wagnert for your hard work and dedication on this project (and your patience with me)!

**Comment by wagnert** [comment]
@HarmonyR You're welcome, like to hear that things work now :). Regarding the UTF-8 BOM from Excel, I'm wondering that Magento Standard Import will process it without any problems, but I'll check this and let's see if we can also find a solution for that :).
